version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - character-set-server=utf8mb4
    volumes:
      - "./data/mysql:/var/lib/mysql"
